jobs:
  build:
    docker:
      - image: cimg/base:stable                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: echo "This is a build step"          # similar to "script" in GitLab

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "This is a test step"

  zap_baseline:
    machine: true
    steps:
      - checkout

      - run: |
          docker pull hysnsec/zap:2.16.1
          docker run --user root --rm -v $(pwd):/zap/wrk:rw -w /zap hysnsec/zap:2.16.1 zap-baseline.py -t https://prod-hmrer927.lab.practical-devsecops.training -J zap-output.json || true

      - store_artifacts:
          path: zap-output.json
          destination: zap-artifact

  prod:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "This is a deploy step"

workflows:
  version: 2
  django:
    jobs:
      - build
      - test
      - integration
      - prod:
          type: approval
